### ISSUE TITLE
"panic: close of closed channel" with Windows nodes

### ISSUE THREAD

**Issue by quadespresso** [Mirantis/mcc#393]
## Background

The panic as shown below happens with fair frequency, although not 100% of the time. It's consistent enough that we've had to code around it in our testing toolbox, ie, if the panic is seen in the output, retry up to 2 more times. And fwiw when this panic happens, the return code is `0`.

```bash
[2023-11-08 12:20:18] DEBU [winrm] 35.85.253.72:5986: VERBOSE: Started service containerd 
[2023-11-08 12:20:18] DEBU [winrm] 35.85.253.72:5986: VERBOSE: Started service docker 
[2023-11-08 12:20:18] DEBU [winrm] 35.85.253.72:5986: VERBOSE: Ensured all services are started 
[2023-11-08 12:20:18] DEBU [winrm] 35.85.253.72:5986: VERBOSE:          
[2023-11-08 12:20:18] DEBU [winrm] 35.85.253.72:5986: Updated Docker from 23.0.7, build 603ea1e to 23.0.8-rc1, build fe856da 
[2023-11-08 12:20:18] DEBU [winrm] 35.85.253.72:5986: Installed Containerd 1.6.25-rc.1 
[2023-11-08 12:20:18] DEBU [winrm] 35.85.253.72:5986: VERBOSE:          
[2023-11-08 12:20:18] DEBU [winrm] 35.85.253.72:5986: Install/upgrade completed 
[2023-11-08 12:20:18] DEBU [winrm] 35.85.253.72:5986: executing `del /f "C:\Users\Administrator\installerWindows2054059595.ps1"` 
[2023-11-08 12:20:19] panic: close of closed channel
[2023-11-08 12:20:19] 
[2023-11-08 12:20:19] goroutine 586 [running]:
[2023-11-08 12:20:19] github.com/masterzen/winrm.(*Command).Close(0xc000238a20)
[2023-11-08 12:20:19] 	github.com/masterzen/winrm@v0.0.0-20220917170901-b07f6cb0598d/command.go:123 +0x106
[2023-11-08 12:20:19] github.com/k0sproject/rig.(*WinRM).Exec.func3()
[2023-11-08 12:20:19] 	github.com/k0sproject/rig@v0.10.0/winrm.go:261 +0x3a5
[2023-11-08 12:20:19] created by github.com/k0sproject/rig.(*WinRM).Exec
[2023-11-08 12:20:19] 	github.com/k0sproject/rig@v0.10.0/winrm.go:248 +0x610
```

I found this conversation on Slack that indicates it's been an issue for a while: https://miracloud.slack.com/archives/C0142BD0E3X/p1618413154087300

- <https://mirantis.jira.com/browse/PRODENG-2438>

**Comment by james-nesbitt** [comment]
I think that this is stale now.
